
```{r}
library(stringr)
library(readr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(PupillometryR)
```


```{r}
# upload data
data <- read_csv("mdc_clean1.csv")
head(data)
```

```{r}
# keep numeric variables
data1 <- data[,-c(1,3,4,5,7, 10,11,12,13,14,15)]
data1$entity <- as.factor(data1$entity)
head(data1)
```

```{r}
# plot
p <- data1 %>% 
  pivot_longer(-entity, names_to = "variable", values_to="value") %>%
  ggplot() +
  aes(x = entity,
      y = value,
      fill = entity) +
  geom_point(aes(color = entity),
             position = position_jitter(w = 0.15),
             size =0.5,
             alpha = 0.7) +
  geom_boxplot(width = .25,
               alpha = 0.5) +
  geom_violin(position = position_nudge(x = .2),
              aes(linetype =NA),
                   alpha = 0.5,
                   adjust = 0.5)  +
  facet_wrap(~variable, ncol = 5, scales = "free") +
  guides(fill = guide_legend(title = "Entity",
                             direction = "horizontal",
                             reverse = T),
         color = guide_legend(title = "Entity",
                              direction = "horizontal",
                              reverse = T)) +
  labs(x = "",
       title = "DC vs MARVEL") +
  theme(legend.position = "bottom")
```

```{r}
# save plot
ggsave(file = "eda1.png", p, width = 297, height = 210, units = "mm")
```





