```{r}
library(stringr)
library(readr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(PupillometryR)
library(randomForest)
library(gbm)
library(caret)
library(Matrix)
library(cvms)
library(car)
library(boot)
library(glmnet)
```

```{r}
d <- data[,c(20, 6, 8, 9, 16, 17, 18, 19, 21)]
d <-rename(d, Worldwide_Lifetime_Gross = "Worldwide Lifetime Gross")
d$entity <- as.factor(d$entity)
head(d)
summary(lm(Worldwide_Lifetime_Gross~., data=d))
fit1 <- glm(Worldwide_Lifetime_Gross~., data=d)
summary(fit1)
```

```{r}
pairs(d)
```


```{r}
results<- data.frame(degree = 1:5, cv.error_k5 = NA)
set.seed(1000)

for (i in 1:5){
fit4 = glm(Worldwide_Lifetime_Gross~entity + poly(runtime, i) + poly(imdb_rating, i) + poly(imdb_votes, i) + poly(tomato_meter, i) + poly(tomato_review , i) + poly(tom_aud_score , i) + poly(tom_ratings , i), data=d)
cv.error_k5 <- cv.glm(d, fit4, K = 5)
results$cv.error_k5[i] <- cv.error_k5$delta[1] }
plot(results$degree, results$cv.error_k5, type='b')
```

```{r}
summary(lm(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_rating, 2) + poly(imdb_votes, 2) + poly(tomato_meter, 2) + poly(tomato_review , 2) + poly(tom_aud_score , 2) + poly(tom_ratings , 2), data=d))
fit2 = glm(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_rating, 2) + poly(imdb_votes, 2) + poly(tomato_meter, 2) + poly(tomato_review , 2) + poly(tom_aud_score , 2) + poly(tom_ratings , 2), data=d)
summary(fit2)
```

```{r}
summary(lm(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_votes, 2) + poly(tomato_review, 2), data=d))
fit3 = glm(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_votes, 2) + poly(tomato_review, 2), data=d)
summary(fit3)
```


```{r}
# LASSO
x <- model.matrix(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_rating, 2) + poly(imdb_votes, 2) + poly(tomato_meter, 2) + poly(tomato_review , 2) + poly(tom_aud_score , 2) + poly(tom_ratings , 2), d)[,-1]
# Outcome variable
y <- d$Worldwide_Lifetime_Gross

set.seed(1000)
cv <- cv.glmnet(x, y, alpha = 1)
# Display the best lambda value
cv$lambda.min

model <- glmnet(x, y, alpha = 1, lambda = cv$lambda.min)
coef(model)
predictions <- model %>% predict(x) %>% as.vector()
# Model performance metrics
data.frame(
RMSE = RMSE(predictions, d$Worldwide_Lifetime_Gross),
Rsquare = R2(predictions, d$Worldwide_Lifetime_Gross)
)
```

```{r}
# Ridge
x <- model.matrix(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_rating, 2) + poly(imdb_votes, 2) + poly(tomato_meter, 2) + poly(tomato_review , 2) + poly(tom_aud_score , 2) + poly(tom_ratings , 2), d)[,-1]
# Outcome variable
y <- d$Worldwide_Lifetime_Gross

set.seed(1000)
cv <- cv.glmnet(x, y, alpha = 0)
# Display the best lambda value
cv$lambda.min

model <- glmnet(x, y, alpha = 0, lambda = cv$lambda.min)
coef(model)
predictions <- model %>% predict(x) %>% as.vector()
# Model performance metrics
data.frame(
RMSE = RMSE(predictions, d$Worldwide_Lifetime_Gross),
Rsquare = R2(predictions, d$Worldwide_Lifetime_Gross)
)
```


```{r}
predict.regsubsets=function(object,newdata,id,...){
form=as.formula(object$call[[2]])
mat=model.matrix(form,newdata)
coefi=coef(object,id=id)
xvars=names(coefi)
mat[,xvars]%*%coefi
}

k=5
set.seed(1000)
folds=sample(1:k,nrow(d),replace=TRUE)
cv.errors=matrix(NA,k,1, dimnames=list(NULL, paste(1:1)))
```

```{r}
# 5-fold cros-validation
# LASSO
for(j in 1:k){
  x <- model.matrix(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_rating, 2) + poly(imdb_votes, 2) + poly(tomato_meter, 2) + poly(tomato_review , 2) + poly(tom_aud_score , 2) + poly(tom_ratings , 2), d[folds!=j,])[,-1]
  x1 <- model.matrix(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_rating, 2) + poly(imdb_votes, 2) + poly(tomato_meter, 2) + poly(tomato_review , 2) + poly(tom_aud_score , 2) + poly(tom_ratings , 2), d[folds==j,])[,-1]
  y <- d[folds!=j,]$Worldwide_Lifetime_Gross
  set.seed(1000)
  cv <- cv.glmnet(x, y, alpha = 1)
  model <- glmnet(x, y, alpha = 1, lambda = cv$lambda.min)
  pred=predict(model,x1) %>% as.vector()
  cv.errors[j,1]=mean( (d$Worldwide_Lifetime_Gross[folds==j]-pred)^2) 
} 
(mean.cv.errors=mean(cv.errors[,1]))

#ridge
# LASSO
for(j in 1:k){
  x <- model.matrix(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_rating, 2) + poly(imdb_votes, 2) + poly(tomato_meter, 2) + poly(tomato_review , 2) + poly(tom_aud_score , 2) + poly(tom_ratings , 2), d[folds!=j,])[,-1]
  x1 <- model.matrix(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_rating, 2) + poly(imdb_votes, 2) + poly(tomato_meter, 2) + poly(tomato_review , 2) + poly(tom_aud_score , 2) + poly(tom_ratings , 2), d[folds==j,])[,-1]
  y <- d[folds!=j,]$Worldwide_Lifetime_Gross
  set.seed(1000)
  cv <- cv.glmnet(x, y, alpha = 0)
  model <- glmnet(x, y, alpha = 0, lambda = cv$lambda.min)
  pred=predict(model,x1) %>% as.vector()
  cv.errors[j,1]=mean( (d$Worldwide_Lifetime_Gross[folds==j]-pred)^2) 
} 
(mean.cv.errors=mean(cv.errors[,1]))

# glm -fit1
for(j in 1:k){
  fit1 <- glm(Worldwide_Lifetime_Gross~., data=d[folds!=j,])
  pred=predict(fit1,d[folds==j,])
  cv.errors[j,1]=mean( (d$Worldwide_Lifetime_Gross[folds==j]-pred)^2) 
} 
(mean.cv.errors=mean(cv.errors[,1]))

# glm -fit2
for(j in 1:k){
  fit2 = glm(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_rating, 2) + poly(imdb_votes, 2) + poly(tomato_meter, 2) + poly(tomato_review , 2) + poly(tom_aud_score , 2) + poly(tom_ratings , 2), data=d[folds!=j,])
  pred=predict(fit2,d[folds==j,])
  cv.errors[j,1]=mean( (d$Worldwide_Lifetime_Gross[folds==j]-pred)^2) 
} 
(mean.cv.errors=mean(cv.errors[,1]))

# glm -fit3
for(j in 1:k){
  fit3 = glm(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_votes, 2) + poly(tomato_review, 2), data=d[folds!=j,])
  pred=predict(fit3,d[folds==j,])
  cv.errors[j,1]=mean( (d$Worldwide_Lifetime_Gross[folds==j]-pred)^2) 
} 
(mean.cv.errors=mean(cv.errors[,1]))
```

best model 
```{r}
summary(lm(Worldwide_Lifetime_Gross~entity + poly(runtime, 2) + poly(imdb_votes, 2) + poly(tomato_review, 2), data=d))
```
  


